default_context:
  project_name: 'abcApp'
  project_slug: 'abcapp'
  domain_main: 'abcapp.com'
  domain_staging: 'stag.abcapp.com'
  docker_swarm_stack_name_main: 'abcapp-com'
  docker_swarm_stack_name_staging: 'stag-abcapp-com'
  secret_key: '2cfc0e332d81a6576c55678dfa69f6720f359d793addf2475ae5866a7f086dad'
  first_superuser: 'admin@abcapp.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.abcapp.com", "https://stag.abcapp.com", "https://abcapp.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@abcapp.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin@abcapp.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'abcapp.com'
  traefik_constraint_tag_staging: 'stag.abcapp.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
